apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/piyush0742/AI-assisted-DevOps.git
    targetRevision: main
    path: Kubernetes-files/auth-service

  destination:
    server: https://kubernetes.default.svc
    namespace: auth-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
